### ISSUE TITLE
A bug on the News Page?

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ethereumclassic.github.io#517] opened 2020-07-13 18:44 UTC
![image](https://user-images.githubusercontent.com/48069525/87341193-7ab22080-c549-11ea-844a-e30bfc93e211.png)

**Comment by gitr0n1n** [comment] 2020-07-13 19:13
This appears to be related to your PRs from the recently added news articles. You created a new undefined category called "hard forks" instead of using the call "hardfork". I also see you used "annoucements" instead of "annoucement".

All those currency analytics articles you had added @TheEnthusiasticAs

**Comment by TheEnthusiasticAs** [comment] 2020-07-13 21:00
Thx @gitr0n1n , I saw one more. I will correct by myself tommorow.

**Comment by gitr0n1n** [comment] 2020-07-13 21:42
Refreshed the site and observed that the issue is now fixed with the merging of https://github.com/ethereumclassic/ethereumclassic.github.io/pull/518

**Closed by gitr0n1n** 2020-07-13 21:42 UTC
Labels: bug, code, content
