### ISSUE TITLE
NEED: Add Network Monitoring Dashboard

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ethereumclassic.github.io#380] opened 2020-03-14 12:05 UTC
Similar to 2miners.

A network health page would be super valuable for the website.

Example:
https://2miners.com/etc-stats/

stats.ethereumclassic.org

**Comment by hitchcott** [comment] 2020-03-14 12:53
How would this be constituted? Duplicate of #307 ?

**Comment by gitr0n1n** [comment] 2020-03-21 18:54
Even if there are redundant sites. I think its valuable to have this on the ethereumclassic.org site rather than pushing to a third party site. Especially when it can be themed up to ETC branding.

I'd trust the .org site over a miner site anyday.

**Comment by gitr0n1n** [comment] 2020-03-21 21:09
I'm thinking we implement https://grafana.com/ for a status page/network monitor. tied to a node like ethercluster.

**Comment by gitr0n1n** [comment] 2020-03-29 13:36
I would love to see this as our network monitor page. Themed up with Phoenix ETC colors and proper attribution to UBIQ, octano, and @xocel
https://twitter.com/OctanoLabs/status/1222332262357835776?s=20

**Comment by gitr0n1n** [comment] 2020-03-29 13:39
running for ETC Mainnet and all testnets would just absolutely be over the top sex appeal to the site.

**Comment by gitr0n1n** [comment] 2020-08-02 12:02
We just had third party network health site that were supported by deprecated clients. IMO, we NEED network health monitoring on the website at this point. We can NOT rely on mining pools/exchanges as the sources of this information.

Due to not monitoring the network from each node and comparing that data, a 3k reorg was executed yesterday. So I believe this is an urgent task.

**Comment by TheEnthusiasticAs** [comment] 2020-08-02 13:12
I am for it

**Comment by q9f** [comment] 2020-08-02 19:48
I'll host one soon(tm)

**Comment by gitr0n1n** [comment] 2021-10-15 22:28
i think we can close this now that there is http://ethereumclassic.net and http://ethclassic.net monitor dashboards.

Unless we intend to host one inside of this repo itself. Thoughts @hitchcott @TheEnthusiasticAs @w1g0 and others?

**Comment by w1g0** [comment] 2021-10-15 22:45
Hosting in this repository and linking the dashboard to the website sounds like a decentralized idea.

**Comment by MrMarioMichel** [comment] 2021-12-18 19:23
Hi I am the node operator behind [ethclassic.net](https://grafana.mariomichel.com/d/5S-6O8VZk/hyperledger-besu-node-at-ethereum-classic?orgId=1&refresh=5s) and wanted to know if some of you have more knowledge then me in docker. I would like to setup a [blockchain explorer]( https://github.com/xops/expedition) and also a [stats](https://besu.hyperledger.org/en/stable/HowTo/Deploy/Lite-Network-Monitor/) site. Just contact me.

**Comment by IstoraMandiri** [comment] 2022-02-28 03:18
Now that we have https://ethereumclassic.org/network/monitors, do we really need a dedicated subdomain?

Otherwise, I would suggest getting one of those services and deply it under a subdomain.

But I think it's outside the scope of this website project. 

@gitr0n1n

**Comment by gitr0n1n** [comment] 2022-02-28 04:40
> Now that we have https://ethereumclassic.org/network/monitors, do we really need a dedicated subdomain?
> 
> Otherwise, I would suggest getting one of those services and deploy/redirect it under a subdomain (ask bob).
> 
> But I think it's outside the scope of this website project. Same for #377 #407 #608
> 
> @gitr0n1n, as this is out of scope for this website's codebase, please close these issues and/or add links to the monitors page?

I tihnk this is the sexiest thing out there right now: https://etclabscore.github.io/nodes-interface/

**Closed** 2022-03-05 03:27 UTC
Labels: enhancement, content, code
